# Generated by Django 6.0.4 on 2026-04-09 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autores", "0001_initial"),
        ("categorias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Título do Livro",
                        max_length=100,
                        verbose_name="título",
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        help_text="Número Único de identificação do Livro",
                        max_length=100,
                        unique=True,
                        verbose_name="ISBN",
                    ),
                ),
                (
                    "ano_publicacao",
                    models.IntegerField(
                        help_text="Ano de Publicação do Livro",
                        verbose_name="ano publicação",
                    ),
                ),
                (
                    "quantidade_total",
                    models.IntegerField(
                        help_text="Quantidade total de livros comprados",
                        verbose_name="quantidade total",
                    ),
                ),
                (
                    "quantidade_disponivel",
                    models.IntegerField(
                        help_text="Quantidade de Livros disponíveis para empréstimos",
                        verbose_name="quantidade disponível",
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        help_text="Nome do Author do Livro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="autor_livro",
                        to="autores.autor",
                        verbose_name="Autor",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        help_text="Nome da Categoria do Livro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categoria_livro",
                        to="categorias.categoria",
                        verbose_name="categoria",
                    ),
                ),
            ],
        ),
    ]
