# Generated by Django 6.0.4 on 2026-04-16 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="livro",
            options={"ordering": ["titulo", "autor", "isbn"]},
        ),
    ]
