# Generated by Django 4.2.6 on 2023-10-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="votos",
            field=models.FloatField(default=0.0),
        ),
    ]
