# Generated by Django 6.0.4 on 2026-04-16 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categorias", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoria",
            options={"ordering": ["nome"]},
        ),
    ]
