# Generated by Django 6.0.4 on 2026-04-16 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("livros", "0002_alter_livro_options"),
        ("membros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emprestimo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_emprestimo",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Data que pegou o livro",
                        verbose_name="data do empréstimo",
                    ),
                ),
                (
                    "data_prevista_devolucao",
                    models.DateField(
                        blank=True,
                        help_text="Data de devolução do livro",
                        null=True,
                        verbose_name="data de devolução",
                    ),
                ),
                (
                    "data_devolucao",
                    models.DateField(
                        blank=True,
                        help_text="Data que ocorreu a devolução",
                        null=True,
                        verbose_name="data da devolução",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Emprestado", "Emprestado"),
                            ("Devolvido", "Devolvido"),
                            ("Atrasado", "Atrasado"),
                        ],
                        default="Emprestado",
                        max_length=10,
                    ),
                ),
                (
                    "livro",
                    models.ForeignKey(
                        help_text="Título do Livro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emprestimo_livro",
                        to="livros.livro",
                        verbose_name="livro",
                    ),
                ),
                (
                    "membro",
                    models.ForeignKey(
                        help_text="Pessoa que pegou o livro emprestado",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emprestar_membro",
                        to="membros.membro",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_emprestimo"],
            },
        ),
    ]
