# Generated by Django 6.0.4 on 2026-04-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome do Autor", max_length=150, verbose_name="nome"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="E-mail do Autor",
                        max_length=254,
                        null=True,
                        verbose_name="email",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True,
                        help_text="Telefone de contato do Autor",
                        max_length=20,
                        null=True,
                        verbose_name="telefone",
                    ),
                ),
            ],
        ),
    ]
