# Generated by Django 6.0.2 on 2026-02-16 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="Author")),
                (
                    "nacionalidade",
                    models.CharField(max_length=150, verbose_name="Nacionalidade"),
                ),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="Data de Nascimento"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
        ),
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título do Livro"),
                ),
                (
                    "preco",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Preço do Livro"
                    ),
                ),
                (
                    "data_publicacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Publicação"
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fk_livro_autor",
                        to="livraria.autor",
                        verbose_name="Autor do Livro",
                    ),
                ),
            ],
        ),
    ]
