# Generated by Django 6.0.2 on 2026-02-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livraria", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="estoque",
            field=models.IntegerField(default=0, verbose_name="Quantidade em estoque"),
            preserve_default=False,
        ),
    ]
