# Generated by Django 6.0.4 on 2026-04-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Membro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome do Membro da Biblioteca",
                        max_length=150,
                        verbose_name="nome",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="E-mail do Membro",
                        max_length=254,
                        null=True,
                        verbose_name="e-mail",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        help_text="Telefone de Contato do Membro",
                        max_length=20,
                        verbose_name="telefone",
                    ),
                ),
                (
                    "documento",
                    models.CharField(
                        help_text="Documento do Membro",
                        max_length=15,
                        verbose_name="documento",
                    ),
                ),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
    ]
